import { tv } from "tailwind-variants";

export const isDisabledVariants = { true: "opacity-50 cursor-not-allowed" } as const;

export const isFocusVisibleVariants = { true: "outline-2 outline-offset-2 outline-focus" } as const;

export const radiusVariants = { sm: "rounded-lg", md: "rounded-xl", lg: "rounded-2xl", full: "rounded-full", none: "rounded-none" } as const;

export const smallRadiusVariants = { sm: "rounded-md", md: "rounded-lg", lg: "rounded-xl", full: "rounded-full", none: "rounded-none" } as const;

export const useVariantAndColorStyles = (extend?: any) => {
  return tv({
    extend: tv(extend || {}),
    base: "relative z-0 flex items-center justify-center overflow-hidden border outline-hidden duration-300",
    variants: {
      variant: {
        solid: "",
        soft: "",
        light: "",
        bordered: "",
        ghost: "",
        faded: "",
        card: "",
        gradient: "",
        animated: "",
        shadow: "",
      },
      color: {
        default: "",
        inverted: "",
        primary: "",
        secondary: "",
        info: "",
        success: "",
        warning: "",
        error: "",
      },
      isHovered: { true: "" },
      isPressed: { true: "scale-95" },
      isFocusWithin: { true: "ring-1" },
      isDisabled: isDisabledVariants,
      isFocusVisible: isFocusVisibleVariants,
    },
    compoundVariants: [
      { color: "inverted", isFocusVisible: true, className: "outline-inverted" },

      { color: "default", isFocusWithin: true, className: { base: "ring-default" } },
      { color: "inverted", isFocusWithin: true, className: { base: "ring-inverted" } },
      { color: "primary", isFocusWithin: true, className: { base: "ring-primary" } },
      { color: "secondary", isFocusWithin: true, className: { base: "ring-secondary" } },
      { color: "info", isFocusWithin: true, className: { base: "ring-info" } },
      { color: "success", isFocusWithin: true, className: { base: "ring-success" } },
      { color: "warning", isFocusWithin: true, className: { base: "ring-warning" } },
      { color: "error", isFocusWithin: true, className: { base: "ring-error" } },

      { variant: "solid", className: "" },
      { variant: "solid", isHovered: true, className: "" },
      { variant: "solid", color: "default", className: "bg-default border-default text-default-foreground" },
      { variant: "solid", color: "default", isHovered: true, className: "bg-default/90" },
      { variant: "solid", color: "inverted", className: "bg-inverted border-inverted text-inverted-foreground" },
      { variant: "solid", color: "inverted", isHovered: true, className: "bg-inverted/90" },
      { variant: "solid", color: "primary", className: "bg-primary border-primary text-primary-foreground" },
      { variant: "solid", color: "primary", isHovered: true, className: "bg-primary/90" },
      { variant: "solid", color: "secondary", className: "bg-secondary border-secondary text-secondary-foreground" },
      { variant: "solid", color: "secondary", isHovered: true, className: "bg-secondary/90" },
      { variant: "solid", color: "info", className: "bg-info border-info text-info-foreground" },
      { variant: "solid", color: "info", isHovered: true, className: "bg-info/90" },
      { variant: "solid", color: "success", className: "bg-success border-success text-success-foreground" },
      { variant: "solid", color: "success", isHovered: true, className: "bg-success/90" },
      { variant: "solid", color: "warning", className: "bg-warning border-warning text-warning-foreground" },
      { variant: "solid", color: "warning", isHovered: true, className: "bg-warning/90" },
      { variant: "solid", color: "error", className: "bg-error border-error text-error-foreground" },
      { variant: "solid", color: "error", isHovered: true, className: "bg-error/90" },

      { variant: "soft", className: "border-transparent" },
      { variant: "soft", isHovered: true, className: "" },
      { variant: "soft", color: "default", className: "bg-default/10 text-default" },
      { variant: "soft", color: "default", isHovered: true, className: "bg-default/20" },
      { variant: "soft", color: "inverted", className: "bg-inverted/10 text-inverted" },
      { variant: "soft", color: "inverted", isHovered: true, className: "bg-inverted/20" },
      { variant: "soft", color: "primary", className: "bg-primary/10 text-primary" },
      { variant: "soft", color: "primary", isHovered: true, className: "bg-primary/20" },
      { variant: "soft", color: "secondary", className: "bg-secondary/10 text-secondary" },
      { variant: "soft", color: "secondary", isHovered: true, className: "bg-secondary/20" },
      { variant: "soft", color: "info", className: "bg-info/10 text-info" },
      { variant: "soft", color: "info", isHovered: true, className: "bg-info/20" },
      { variant: "soft", color: "success", className: "bg-success/10 text-success" },
      { variant: "soft", color: "success", isHovered: true, className: "bg-success/20" },
      { variant: "soft", color: "warning", className: "bg-warning/10 text-warning" },
      { variant: "soft", color: "warning", isHovered: true, className: "bg-warning/20" },
      { variant: "soft", color: "error", className: "bg-error/10 text-error" },
      { variant: "soft", color: "error", isHovered: true, className: "bg-error/20" },

      { variant: "light", className: "border-transparent bg-transparent" },
      { variant: "light", color: "default", className: "text-default" },
      { variant: "light", color: "default", isHovered: true, className: "bg-default/10" },
      { variant: "light", color: "inverted", className: "text-inverted" },
      { variant: "light", color: "inverted", isHovered: true, className: "bg-inverted/10" },
      { variant: "light", color: "primary", className: "text-primary" },
      { variant: "light", color: "primary", isHovered: true, className: "bg-primary/10" },
      { variant: "light", color: "secondary", className: "text-secondary" },
      { variant: "light", color: "secondary", isHovered: true, className: "bg-secondary/10" },
      { variant: "light", color: "info", className: "text-info" },
      { variant: "light", color: "info", isHovered: true, className: "bg-info/10" },
      { variant: "light", color: "success", className: "text-success" },
      { variant: "light", color: "success", isHovered: true, className: "bg-success/10" },
      { variant: "light", color: "warning", className: "text-warning" },
      { variant: "light", color: "warning", isHovered: true, className: "bg-warning/10" },
      { variant: "light", color: "error", className: "text-error" },
      { variant: "light", color: "error", isHovered: true, className: "bg-error/10" },

      { variant: "bordered", className: "bg-transparent" },
      { variant: "bordered", isHovered: true, className: "" },
      { variant: "bordered", color: "default", className: "border-default/50 text-default" },
      { variant: "bordered", color: "default", isHovered: true, className: "bg-default/10" },
      { variant: "bordered", color: "inverted", className: "border-inverted/50 text-inverted" },
      { variant: "bordered", color: "inverted", isHovered: true, className: "bg-inverted/10" },
      { variant: "bordered", color: "primary", className: "border-primary/50 text-primary" },
      { variant: "bordered", color: "primary", isHovered: true, className: "bg-primary/10" },
      { variant: "bordered", color: "secondary", className: "border-secondary/50 text-secondary" },
      { variant: "bordered", color: "secondary", isHovered: true, className: "bg-secondary/10" },
      { variant: "bordered", color: "info", className: "border-info/50 text-info" },
      { variant: "bordered", color: "info", isHovered: true, className: "bg-info/10" },
      { variant: "bordered", color: "success", className: "border-success/50 text-success" },
      { variant: "bordered", color: "success", isHovered: true, className: "bg-success/10" },
      { variant: "bordered", color: "warning", className: "border-warning/50 text-warning" },
      { variant: "bordered", color: "warning", isHovered: true, className: "bg-warning/10" },
      { variant: "bordered", color: "error", className: "border-error/50 text-error" },
      { variant: "bordered", color: "error", isHovered: true, className: "bg-error/10" },

      { variant: "ghost", className: "bg-transparent" },
      { variant: "ghost", isHovered: true, className: "" },
      { variant: "ghost", color: "default", className: "border-default/50 text-default" },
      { variant: "ghost", color: "default", isHovered: true, className: "bg-default border-default text-default-foreground" },
      { variant: "ghost", color: "inverted", className: "border-inverted/50 text-inverted" },
      { variant: "ghost", color: "inverted", isHovered: true, className: "bg-inverted border-inverted text-inverted-foreground" },
      { variant: "ghost", color: "primary", className: "border-primary/50 text-primary" },
      { variant: "ghost", color: "primary", isHovered: true, className: "bg-primary border-primary text-primary-foreground" },
      { variant: "ghost", color: "secondary", className: "border-secondary/50 text-secondary" },
      { variant: "ghost", color: "secondary", isHovered: true, className: "bg-secondary border-secondary text-secondary-foreground" },
      { variant: "ghost", color: "info", className: "border-info/50 text-info" },
      { variant: "ghost", color: "info", isHovered: true, className: "bg-info border-info text-info-foreground" },
      { variant: "ghost", color: "success", className: "border-success/50 text-success" },
      { variant: "ghost", color: "success", isHovered: true, className: "bg-success border-success text-success-foreground" },
      { variant: "ghost", color: "warning", className: "border-warning/50 text-warning" },
      { variant: "ghost", color: "warning", isHovered: true, className: "bg-warning border-warning text-warning-foreground" },
      { variant: "ghost", color: "error", className: "border-error/50 text-error" },
      { variant: "ghost", color: "error", isHovered: true, className: "bg-error border-error text-error-foreground" },

      { variant: "faded", color: "default", className: "border-default/50 bg-default/10 text-default" },
      { variant: "faded", color: "default", isHovered: true, className: "bg-default/20" },
      { variant: "faded", color: "inverted", className: "border-inverted/50 bg-inverted/10 text-inverted" },
      { variant: "faded", color: "inverted", isHovered: true, className: "bg-inverted/20" },
      { variant: "faded", color: "primary", className: "border-primary/50 bg-primary/10 text-primary" },
      { variant: "faded", color: "primary", isHovered: true, className: "bg-primary/20" },
      { variant: "faded", color: "secondary", className: "border-secondary/50 bg-secondary/10 text-secondary" },
      { variant: "faded", color: "secondary", isHovered: true, className: "bg-secondary/20" },
      { variant: "faded", color: "info", className: "border-info/50 bg-info/10 text-info" },
      { variant: "faded", color: "info", isHovered: true, className: "bg-info/20" },
      { variant: "faded", color: "success", className: "border-success/50 bg-success/10 text-success" },
      { variant: "faded", color: "success", isHovered: true, className: "bg-success/20" },
      { variant: "faded", color: "warning", className: "border-warning/50 bg-warning/10 text-warning" },
      { variant: "faded", color: "warning", isHovered: true, className: "bg-warning/20" },
      { variant: "faded", color: "error", className: "border-error/50 bg-error/10 text-error" },
      { variant: "faded", color: "error", isHovered: true, className: "bg-error/20" },

      { variant: "card", className: "border-default-1000/20 bg-default-0" },
      { variant: "card", isHovered: true, className: "bg-default-100" },
      { variant: "card", color: "default", className: "text-default" },
      { variant: "card", color: "inverted", className: "text-inverted border-default-0/20 bg-default-1000" },
      { variant: "card", color: "inverted", isHovered: true, className: "bg-default-900" },
      { variant: "card", color: "primary", className: "text-primary" },
      { variant: "card", color: "secondary", className: "text-secondary" },
      { variant: "card", color: "info", className: "text-info" },
      { variant: "card", color: "success", className: "text-success" },
      { variant: "card", color: "warning", className: "text-warning" },
      { variant: "card", color: "error", className: "text-error" },

      { variant: "gradient", className: "border-transparent bg-linear-to-b [background-size:200%_200%;]" },
      { variant: "gradient", isHovered: true, className: "[background-position:100%_100%;]" },
      { variant: "gradient", color: "default", className: "from-default via-default/50 to-default text-default-foreground" },
      { variant: "gradient", color: "inverted", className: "from-inverted via-inverted/50 to-inverted text-inverted-foreground" },
      { variant: "gradient", color: "primary", className: "from-primary via-primary/50 to-primary text-primary-foreground" },
      { variant: "gradient", color: "secondary", className: "from-secondary via-secondary/50 to-secondary text-secondary-foreground" },
      { variant: "gradient", color: "info", className: "from-info via-info/50 to-info text-info-foreground" },
      { variant: "gradient", color: "success", className: "from-success via-success/50 to-success text-success-foreground" },
      { variant: "gradient", color: "warning", className: "from-warning via-warning/50 to-warning text-warning-foreground" },
      { variant: "gradient", color: "error", className: "from-error via-error/50 to-error text-error-foreground" },

      {
        variant: "animated",
        className:
          "border-transparent before:absolute before:inset-x-0 before:-z-10 before:aspect-square before:animate-spin before:bg-linear-to-b before:duration-300 before:duration-[3s]",
      },
      { variant: "animated", isHovered: true, className: "before:opacity-0" },
      { variant: "animated", color: "default", className: "before:from-default/10 before:to-default/20 text-default" },
      { variant: "animated", color: "default", isHovered: true, className: "bg-default text-default-foreground" },
      { variant: "animated", color: "inverted", className: "before:from-inverted/10 before:to-inverted/20 text-inverted" },
      { variant: "animated", color: "inverted", isHovered: true, className: "bg-inverted text-inverted-foreground" },
      { variant: "animated", color: "primary", className: "before:from-primary/10 before:to-primary/20 text-primary" },
      { variant: "animated", color: "primary", isHovered: true, className: "bg-primary text-primary-foreground" },
      { variant: "animated", color: "secondary", className: "before:from-secondary/10 before:to-secondary/20 text-secondary" },
      { variant: "animated", color: "secondary", isHovered: true, className: "bg-secondary text-secondary-foreground" },
      { variant: "animated", color: "info", className: "before:from-info/10 before:to-info/20 text-info" },
      { variant: "animated", color: "info", isHovered: true, className: "bg-info text-info-foreground" },
      { variant: "animated", color: "success", className: "before:from-success/10 before:to-success/20 text-success" },
      { variant: "animated", color: "success", isHovered: true, className: "bg-success text-success-foreground" },
      { variant: "animated", color: "warning", className: "before:from-warning/10 before:to-warning/20 text-warning" },
      { variant: "animated", color: "warning", isHovered: true, className: "bg-warning text-warning-foreground" },
      { variant: "animated", color: "error", className: "before:from-error/10 before:to-error/20 text-error" },
      { variant: "animated", color: "error", isHovered: true, className: "bg-error text-error-foreground" },

      { variant: "shadow", className: "border-transparent shadow-[0_2px_8px]" },
      { variant: "shadow", isHovered: true, className: "shadow-[0_2px_4px]" },
      { variant: "shadow", color: "default", className: "bg-default shadow-default text-default-foreground" },
      { variant: "shadow", color: "inverted", className: "bg-inverted shadow-inverted text-inverted-foreground" },
      { variant: "shadow", color: "primary", className: "bg-primary shadow-primary text-primary-foreground" },
      { variant: "shadow", color: "secondary", className: "bg-secondary shadow-secondary text-secondary-foreground" },
      { variant: "shadow", color: "info", className: "bg-info shadow-info text-info-foreground" },
      { variant: "shadow", color: "success", className: "bg-success shadow-success text-success-foreground" },
      { variant: "shadow", color: "warning", className: "bg-warning shadow-warning text-warning-foreground" },
      { variant: "shadow", color: "error", className: "bg-error shadow-error text-error-foreground" },
    ],
  });
};

export const useHelperButtonStyles = () =>
  tv({
    base: [
      "relative z-10 flex min-w-max cursor-pointer items-center justify-center overflow-hidden whitespace-nowrap outline-hidden transition-transform duration-300",
      "before:absolute before:inset-0 before:-z-10 before:bg-current data-pressed:scale-90",
      "data-disabled:cursor-not-allowed data-disabled:opacity-50 data-focus-visible:outline-offset-0 data-focus-visible:outline-current",
    ],
    variants: {
      variant: {
        soft: "before:opacity-10 data-hovered:before:opacity-20",
        light: "before:opacity-0 data-hovered:before:opacity-10",
      },
    },
    defaultVariants: { variant: "soft" },
  });
